Api Keys are now stored hashed in DB
stevespringett/Alpine pull request #687
Opened 2024-10-14 12:08 UTC by Gepardgame

### Description

This PR addresses [#532](https://github.com/stevespringett/Alpine/issues/532#issuecomment-2378988533) by changing from API Keys being stored in plain to be stored as a hash.

Will be hashed with bcrypt. Only at creation time are once returned in plain, so it can be used. Adds a suffix to the API Key, on which the key will be retrieved from the db. Masked Key is now at the ending the suffix. Hashed Key will be also not returned in the API.

2024-10-18 15:57 UTC, nscuro requested changes
Thanks for the PR. A few comments.

Also, do you have a migration strategy in mind for this? How do we deal with existing API keys that are *not* hashed yet?

2024-10-18 15:57 UTC, nscuro commented on alpine-infra/src/main/java/alpine/persistence/AlpineQueryManager.java
> +            apiKey.setKey(clearKey + apiKey.getSuffix());
Any reason for generating a new random value for the suffix? Shouldn't it just be the last N characters of the API key?

2024-10-18 15:57 UTC, nscuro commented on alpine-infra/src/main/java/alpine/persistence/AlpineQueryManager.java
> +            return BCrypt.checkpw(key.substring(0, key.length() - SUFFIX_LENGTH), apiKey.getKey()) ? apiKey : null;
Keep in mind that `apiKey` can be null if no matching record was found in the database.

2024-10-21 12:13 UTC, Gepardgame commented
> Also, do you have a migration strategy in mind for this? How do we deal with existing API keys that are not hashed yet?

Simpliest way would be to provide a script, that simply gets every key, hashs it and update it in the DB. Would that suffice, or should it something be, there the user doesn't need to do anything? Then maybe temporarily support both and update it in the code, and after a while only support hashed ones. Or maybe add a function to the code that once gets all keys and updates them. That way you need to once upgrade to this version to get it to work later.

2024-10-21 14:13 UTC, Gepardgame commented
2 things remaining:
1. when response contains an API Key, key value should not be showen, only if you create/regenerate it.
2. Team Creation should no longer support creating Api key, as the Clear API Key is never returned, and therefore cannot be used.

2024-10-21 14:14 UTC, Gepardgame commented
2 things remaining:
1. when response contains an API Key, key value should not be showen, only if you create/regenerate it.
2. Team Creation should no longer support creating Api key, as the Clear API Key is never returned, and therefore cannot be used.

2024-11-27 07:14 UTC, Gepardgame commented
@nscuro  In Team Creation its no longer possible to create an api Key, which was never even used in DT.
About returning the key or not, that qould need to be done in DT, and the upgrading as well, cause we don't have  upgrade scripts in ALpine directly, but only  in DT then, as far as I know

2025-01-09 09:13 UTC, Gepardgame commented
The ci error seems not to be on my side, I didn't touch the cache manager

2025-01-11 19:20 UTC, nscuro reviewed
I did a bit more research and it seems like your initial implementation (where you generated an additional random value for the suffix) was the better one after all.

The best, concise resource on this topic I could find is this: https://glama.ai/blog/2024-10-18-what-makes-a-good-api-key

Oddly enough there doesn't seem to be one from OWASP. Anyway, under *Designing the perfect API key* the author mentions:

> * The key should have a prefix that describes the workspace that owns the key.

We have this already, defaulting to `alpine_` but overwritten to `odt_` for Dependency-Track.

> * The key should have a stable fragment that can be used as public key identifier.

This would be the suffix you generated in the initial implementation. The important part is that this value should not be part of the actual key itself, as I wrongly suggested during the last review.

> * The key itself should encode information that is useful for troubleshooting purposes (e.g., user ID).

I guess this would change the key structure too much, so best to ignore this one for now.

The example structure they provide is:

```
<prefix>_<public key identifier>.<encoded payload>
```

In our case, this would be:

```
<prefix>_<public key identifier>.<key>
```

where `public key identifier` would be what previously was `suffix`. The benefit of keeping it separate is that we can include this public identifier in logs, and display it in the UI, without leaking parts of the actual key.

Another good article on this here: https://www.freecodecamp.org/news/best-practices-for-building-api-keys-97c26eabfea9/

Examples of this in the wild:

* https://docs.dynatrace.com/docs/discover-dynatrace/references/dynatrace-api/basics/dynatrace-api-authentication#token-format
* https://developer.hosting.ionos.de/docs/getstarted#createKey
* https://github.com/seamapi/prefixed-api-key

The downside of doing it like this: Existing keys would become invalid, since the public identifier is a new addition that was previously not part of the key that clients provide when authenticating. But we could add some sort of fallback logic to avoid this.

Thoughts @Gepardgame?

2025-01-13 07:54 UTC, Gepardgame commented
> `<prefix>_<public` key `identifier>.<key>`

So this is the key the user gets
>  `<key>`

and this is that is actually hashed in the db? So nothing what is publicly knowed is is should be hashed.

The thing with encoding things in the key it self, I don't know what it gets us. Much simpler would it be, to make an endpoint, to which the apikey can authenticte, and it return information about it, like to whom it belongs and such stuff.

> The downside of doing it like this: Existing keys would become invalid, since the public identifier is a new addition that was previously not part of the key that clients provide when authenticating. But we could add some sort of fallback logic to avoid this.

A workaround could be to the first 5 chars of the key for the public identifier, effectively making the key, that is being hashed, shorter and simply say that this will in a future version no longer work, giving time to change.

2025-01-13 11:09 UTC, nscuro reviewed
> The thing with encoding things in the key it self, I don't know what it gets us.

Yeah with you on this one, I don't think it's particularly useful either.

> A workaround could be to the first 5 chars of the key for the public identifier, effectively making the key, that is being hashed, shorter and simply say that this will in a future version no longer work, giving time to change.

That sounds reasonable. But I think we might need a way to make it visible to users if a key is using the "legacy" format. We could add a new `boolean isLegacy` column or so, which we set during the migration. This would enable us to highlight such keys in the UI. Users can then go ahead and generate new keys to replace the legacy ones. WDYT?

A new `boolean` column can safely be added like this: https://github.com/DependencyTrack/dependency-track/blob/16a4edf67eb4b3035cf6f99c97e5fd5960b38c20/src/main/java/org/dependencytrack/model/ProjectMetrics.java#L179-L180

Separately, I think it would be good to have a test that ensures that keys we generate via `AlpineQueryManager#createApiKey` and `AlpineQueryManager#regenerateApiKey` can be used to authenticate, and that invalid keys are rejected.

There is currently no test for `ApiKeyAuthenticationService`, but you could take inspiration from [`JwtAuthenticationServiceTest`](https://github.com/stevespringett/Alpine/blob/master/alpine-server/src/test/java/alpine/server/auth/JwtAuthenticationServiceTest.java) to create one.

2025-01-13 13:13 UTC, Gepardgame commented on alpine-common/src/main/java/alpine/Config.java
> +        API_KEY_PUBLIC_ID_LENGTH               ("alpine.api.key.public.id.length",   5),
I need the number on two different location, and don't wanted to have it on multiply locations set, but rather at one. If you how to accomplish other than that, I can change it accordingly.

2025-01-17 13:04 UTC, nscuro approved these changes
Great work @Gepardgame, thanks!

2025-01-17 13:04 UTC, merged

2025-01-17 13:18 UTC, nscuro commented
@Gepardgame I have [published](https://oss.sonatype.org/content/repositories/snapshots/us/springett/alpine-parent/3.2.0-SNAPSHOT/) Alpine `3.2.0-SNAPSHOT`. If you like, you could work on a PR for Dependency-Track that bumps Alpine to this version and performs the necessary API key migration.

2025-01-20 13:40 UTC, Gepardgame commented
@nscuro The migration per se works, but as I changed that the key is ignored for json serialization, I need to return the key somehow otherwise for the (re)generation, any good idea on that? Via doing the json myself or custom Class jsut for that? I also saw, that most api endpoints that involve the API Key, need the key to be in the url, as parameter, I think thats not the best way (like add comment, regen, delete). I think for that can the public ID be used instead, as you still need to be admin to access this endpoints at all. I also saw, if you list all teams, a masked api key looks like that: "OyNYO*******************************************************" (is from local testing). There is no prefix, because it gens it from the keys out of the db, which are hashed and don't have the prefix. I will add a PR for the things related to Alpine it self.